### ISSUE TITLE
Blog Post Pictures not showing.

### ISSUE THREAD

**Issue by ivan20203** [zk-passport/proofofpassport.com#20]
https://blog.openpassport.app/

Google Chrome.

<img width="1418" alt="Screenshot 2024-09-09 at 21 21 22" src="https://github.com/user-attachments/assets/9f24d0e2-0c45-426c-bddb-d7fe78aa1657">

**Comment by 0xturboblitz** [comment]
Thanks for letting us know! Just fixed it
